<?php
  function user_greetings_menu() {
    $items = array();
    $items['hello_user'] = array(
      'title' => "Welcome User!",
      'page callback' => 'say_hello',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['goodbye'] = array(
      'title' => "Thanks for visting!",
      'page callback' => 'say_goodbye',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function say_hello() {
    return "<p> Hello, and welcome to Cameron's Coffee! We hope you will enjoy your stay. Checkout some of our newest coffee options on our homepage.</p>";
  }

  function say_goodbye() {
    return "<p> Goodbye for now! Thank you for visiting Cameron's Coffee. We hope you found what you were looking for, and you will be back again soon!";
  }

  function user_greetings_user_login() {
      global $user;
      $role = '';
      if(in_array('administrator', $user->roles)) {
          drupal_set_message('Greetings, overlord.');
          $role = 'administrator';
      } elseif (in_array('authenticated user', $user->roles)) {
          drupal_set_message('Welcome back piehole apprentice.');
          $role = 'authenticated user';
      } else {
          drupal_set_message('Piss off, you unauthorized entity!');
      }
      user_greetings_cookie_save(array($role));
      $_GET['destination']='say_hello';
  }

  function user_greetings_user_logout() {
    $_GET['destination']='say_goodbye';
  }
