<?php

function ping_pong_menu() {
  $items['ping_pong'] = array(
    'title' => 'Ping Pong Problem',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ping_pong_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['ping_pong_sucess'] = array(
    'title' => 'Sucess',
    'page callback' => 'ping_pong_sucess',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function ping_pong_form() {
  $form['count_goal'] = array(
    '#title' => 'Count Goal',
    '#type' => 'textfield',
    '#description' => t('Please enter the number you want to count up to.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );

  return $form;
}

function ping_pong_form_submit($form, &$form_state) {
  $count_max = $form_state['values']['count_goal'];
  $output = array();

  for($i = 1; $i <= $count_max; $i++) {
    if( $i % 3 === 0 && $i % 5 === 0) {
      array_push($output, "ping-pong!");
    } elseif ($i % 3 === 0) {
      array_push($output, "ping!");
    } elseif ($i % 5 === 0) {
      array_push($output, "pong!");
    } else {
      array_push($output, $i);
    }
  }
  $_SESSION['output'] = $output;
  $form_state['redirect'] = 'ping_pong_sucess';
}

function ping_pong_sucess() {
  $output = '<ul>';
  foreach($_SESSION['output'] as $value){
    $output = $output . '<li>' . $value . '</li>';
  }
  $output = $output . "</ul>";
  return "Hooray! $output";
}
