<?php
function comment_menu(){
  $items = array();
  $items['comment_save'] = array(
    'title' => 'Comment saved!',
    'page callback' => 'comment_save',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['commment_delete'] = array(
    'title' => "Comment Deleted",
    'page callback' => 'comment_delete',
    'access callback' =>  TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

// using hook_comment
// hyper link to guide for Drupal 7 hooks
// https://api.drupal.org/api/drupal/includes!module.inc/group/hooks/7.x

function comment_save() {
  return "<p> Your comment has been saved.</p>";
}

function comment_delete() {
  return "<p> Your comment has been delete.";
}

function comment_comment_publish() {
  $_GET['destination'] = 'comment_save';
}

function comment_comment_delete() {
  $GET_['destination'] = "comment_delete";
}
